config/routes.rb
Rails.application.routes.draw do

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end


  resources :categories, except: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :favorites, only: [:create, :destroy, :index]
  resources :products, path: '/'
  resources :users, only: :show, path: '/user', param: :username
 
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable
  has_one_attached :photo
  belongs_to :category
  belongs_to :user, default: -> { Current.user }
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }, using: {
    tsearch: { prefix: true } # Use the trigram index method
  }

  ORDER_BY = {
    newest: 'created_at DESC',
    expensive: 'price DESC',
    cheapest: 'price ASC'
  }

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def owner?
    user_id == Current.user&.id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: %i[new create index]
  skip_before_action :authenticate_user, only: [:index, :show]

  def index
    @categories = Category.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(secure_params)

    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize! product
    if @product.update(secure_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! product
    @product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  def edit
    authorize! product
  end

  private

  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)
  end

  def set_product
    @product ||= Product.find(params[:id])
  end

  def secure_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite.html.erb
<div id="favorite">
  <% if product.favorite %>
    <%= link_to '💔', favorite_path(product.id), data: {
      turbo_method: :delete
    } %>
  <% else %>
    <%= link_to '❤️', favorites_path(product_id: product.id), data: {
      turbo_method: :post
    } %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
   <div>
    <%= form.text_field :title, placeholder: t(".title_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.text_area :description, placeholder: t(".description_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full", rows: 5 %>
  </div>

  <div>
    <%= form.number_field :price, placeholder: t(".price_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: t(".category_placeholder") }, { class: "rounded-2xl border-gray-200 mb-4 w-full text-gray-500"} %>
  </div>

  <div class="rounded-2xl border-gray-200 mb-4 w-full border-[1px] p-2 text-gray-500">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit t('.submit'), class: "px-4 py-2 font-semibold text-sm bg-cyan-500 text-white rounded-2xl cursor-pointer shadow-sm" %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product bg-white mb-2 rounded sm:w-[calc(33.33333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)]', 'data-turbo-frame': '_top' do %>
    <%= image_tag product.photo.attached? ? product.photo : 'placeholder.jpg', class: "w-full h-60 object-cover" if product.photo.attached? %>
    <div class="m-2">
        <span class="font-bold text-xl"><%= product.price %>$</span>
        <h2 class=""><%= product.title %></h2>
        <p class="text-gray-500 text-sm mt-2"><%= product.description %></p>
    </div>
<% end %>

app/views/products/edit.html.erb
<h2><%= t('.title')%></h2>
<%= render 'form'%>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full my-2 rounded-2xl border-gray-200" %>

    <div class="flex">
      <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-2xl border-gray-200" %>

      <%= form.number_field :max_price, placeholder: t('.max_price'),onChange: 'this.form.requestSubmit()', value: params[:max_price], class: "w-1/3 rounded-2xl border-gray-200 mx-2" %>

      <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class: "w-1/3 rounded-2xl border-gray-200 text-gray-500" } %>
    </div>
  <% end %>

  <div class="flex overflow-x-scroll gap-2 my-4">
    <%= render(CategoryComponent.new) %>
    <%= render(CategoryComponent.with_collection(@categories)) %>
  </div>

  <%= turbo_frame_tag :products, class: "flex flex-col m-2" do %>
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2' do %>
      <%= render partial: 'product', collection: @products %>
      <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p class="cursor-pointer mb-4" data-action="click->modal#close">❌</p>
      <h2 class="font-bold mb-4"><%= t('.title') %></h2>

      <%= render 'form' %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<% if @product.photo.attached? %>
  <%= image_tag @product.photo, width: 100 %>
<% end %>
<h1 class='title'><%= @product.title %></h1>
<p  class='description'> <%= @product.description %></p>
<span class='price'><%= @product.price %>$</span>
<%= link_to t('.edit'), edit_product_path(@product) if @product.owner?%>
<%= link_to t('.delete'), product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: 'Are you sure?'
} if @product.owner? %>

<%= link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username) %>



<%= render partial: 'favorite', locals: { product: @product } %>